### ISSUE TITLE
'Segment_Branch/BNCBranchIntegrationFactory.h' file not found

### ISSUE THREAD

**Issue by sathish-xe** [claimsforce-gmbh/flutter-segment#31]
I'm getting 'Segment_Branch/BNCBranchIntegrationFactory.h' file not found while building the project.

Similar [issue](https://github.com/segmentio/analytics-react-native/issues/30) is posted in react-native plugin. How do I solve this in flutter? Please help me out.

**Using plugin**
`flutter_segment: ^2.1.1`

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.3 19D76, locale en-GB)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[!] Connected device
    ! No devices available
```

**Comment by MaiKaY** [comment]
Fixed in `2.2.0`

**Comment by FilledStacks** [comment]
Hi @MaiKaY I'm getting the same error as above in v 2.2.0

```
 /Users/danemackier/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_segment-2.2.0/ios/Classes/FlutterSegmentPlugin
    .m:5:9: fatal error: 'Segment-Branch/BNCBranchIntegrationFactory.h' file not found
    #import <Segment-Branch/BNCBranchIntegrationFactory.h>
```

flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.5 19F101, locale en-ZA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.48.2)
[✓] Connected device (1 available)

• No issues found!
```

Did a flutter clean, rebuild, flutter clean, removed pods, removed pod files, ran flutter pub upgrade, etc. Multiple times. Nothing seems to work.

**Comment by MaiKaY** [comment]
Hi @FilledStacks,
have you tried to run `pod repo update` in the `ios` directory?

**Comment by yuripiratello** [comment]
Hello guys! What I found:

- The import on `flutter_segment/ios/Classes/FlutterSegmentPlugin.m` are with `-` (https://github.com/claimsforce-gmbh/flutter-segment/blob/master/ios/Classes/FlutterSegmentPlugin.m#L5)
![image](https://user-images.githubusercontent.com/559315/91867505-19095b00-ec4a-11ea-8156-a857dbe57196.png)
![image](https://user-images.githubusercontent.com/559315/91867532-1f97d280-ec4a-11ea-8207-c90dde218961.png)

- The framework generated is with `_`
![image](https://user-images.githubusercontent.com/559315/91867539-21fa2c80-ec4a-11ea-977c-30e11b376912.png)

So if I change the import from `-` to `_` the errors disappear. 
![image](https://user-images.githubusercontent.com/559315/91867656-448c4580-ec4a-11ea-80ab-a048393b8a11.png)
![image](https://user-images.githubusercontent.com/559315/91867675-4950f980-ec4a-11ea-8032-3396a2be8f75.png)


When I changed the version of flutter_segment from `2.2.0` to `2.0.2` the build and run worked fine.

**Comment by FilledStacks** [comment]
@MaiKaY Yes I have. @yuripiratello nice find. I will test this out when I get back to the segment scheme implementation. thanks for sharing.

**Comment by MaiKaY** [comment]
Sadly, it feels that the whole thing is a neverending story.

On the 12th of May 2020 we initially set it to [`Segment_Branch`](https://github.com/claimsforce-gmbh/flutter-segment/commit/89f57c33876a001d592acf749f22cdd16197ed70#diff-d4ee3f428d7eabd6d93eb5eb26e750d7) after this release we got feedback that this namespace is wrong, therefore it was changed on the 14th of July 2020 to [`Segment-Branch `](https://github.com/claimsforce-gmbh/flutter-segment/commit/ea683bd461c94f7384e5e56ae9d6307f31d0797b#diff-d4ee3f428d7eabd6d93eb5eb26e750d7).

Personally **I don't know** what to correct path should be and why it works for some with `Segment_Branch` and for some with `Segment-Branch`.

As next steps:
I will set a specific `Segment-Branch` version in `flutter_segment.podspec`. And change the namespace back to `Segment_Branch`. After that it would be cool if you guys (@FilledStacks, @yuripiratello) can help me in testing it.

**Comment by MaiKaY** [comment]
I released `2.2.1`, I am more than happy if you can assist me by testing it.

**Comment by FilledStacks** [comment]
@MaiKaY give me a few minutes. I'll jump on that branch now and test it out. Will report back in a bit

**Comment by FilledStacks** [comment]
Didnd't work for me Still getting this error. 

```
 /Users/danemackier/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_segment-2.2.1/ios/Classes/FlutterSegmentPlugin.m:6
    :9: fatal error: 'Segment-Amplitude/SEGAmplitudeIntegrationFactory.h' file not found
    #import <Segment-Amplitude/SEGAmplitudeIntegrationFactory.h>
```

Tried 2.0.2 but my ios builds are not working when using that either.

**Comment by abed-binary** [comment]
We had the same problem earlier today, so we traced what changed in version 2.2.0. The problem was with the `-` that should be `_` at Segment-Branch. I don't know what caused this!
We changed it from ios/.symlinks/plugins/flutter_segment/ios/Classes/FlutterSegmentPlugin.m 
The 2 imports should look like this;
`#import <Segment_Branch/BNCBranchIntegrationFactory.h>`
`#import <Segment_Amplitude/SEGAmplitudeIntegrationFactory.h>`

And it is working fine now.

**Comment by MaiKaY** [comment]
Since `Segment_Amplitude` is also effected I just released `2.2.2`. Could you please verify that it solved your problem?

**Comment by abed-binary** [comment]
Yes I can confirm that 2.2.2 solved the problem. 

Thank you

**Comment by MaiKaY** [comment]
Great. Will close this issue. Feel free to reopen in case you need further help.

**Comment by EhabSalah** [comment]
Should segment and amplitude decoupled from each other ??

am facing this error `'Segment-Amplitude/SEGAmplitudeIntegrationFactory.h' file not found`
while build iOS project.

**Comment by danielgomezrico** [comment]
@EhabSalah which version of `flutter_segment` are you using?

**Comment by EhabSalah** [comment]
> @EhabSalah which version of `flutter_segment` are you using?

Currently migrated to `3.3.0` and it works fine on ios with the deprecated configuration for ios, thank you very much @danielgomezrico 😊
