### ISSUE TITLE
Getting "MissingPluginException(No implementation found for method track on channel flutter_segment)"

### ISSUE THREAD

**Issue by bejavu** [claimsforce-gmbh/flutter-segment#6]
Some times, I am getting `MissingPluginException(No implementation found for method track on channel flutter_segment)` error.

```
MissingPluginException: MissingPluginException(No implementation found for method track on channel flutter_segment)
  File "platform_channel.dart", line 319, in MethodChannel.invokeMethod
  File "<asynchronous suspension>"
  File "flutter_segment.dart", line 23, in FlutterSegment.track
  File "store.dart", line 55, in AppFactory.getStore
  File "<asynchronous suspension>"
  File "main.dart", line 38, in main.<fn>.<fn>
  File "zone.dart", line 1126, in _rootRun
  File "zone.dart", line 1023, in _CustomZone.run
  File "zone.dart", line 1518, in _runZoned
  File "zone.dart", line 1502, in runZoned
  File "main.dart", line 34, in main.<fn>
  File "zone.dart", line 1134, in _rootRunUnary
  File "zone.dart", line 1031, in _CustomZone.runUnary
  File "future_impl.dart", line 139, in _FutureListener.handleValue
  File "future_impl.dart", line 680, in Future._propagateToListeners.handleValueCallback
  File "future_impl.dart", line 709, in Future._propagateToListeners
  File "future_impl.dart", line 524, in Future._completeWithValue
  File "async_patch.dart", line 32, in _AsyncAwaitCompleter.complete
  File "async_patch.dart", line 290, in _completeOnAsyncReturn
  File "system_chrome.dart", line 0, in SystemChrome.setPreferredOrientations
  File "<asynchronous suspension>"
  File "main.dart", line 31, in main
  File "<asynchronous suspension>"
  File "hooks.dart", line 239, in _runMainZoned.<fn>.<fn>
  File "zone.dart", line 1126, in _rootRun
  File "zone.dart", line 1023, in _CustomZone.run
  File "zone.dart", line 1518, in _runZoned
  File "zone.dart", line 1502, in runZoned
  File "hooks.dart", line 231, in _runMainZoned.<fn>
  File "isolate_patch.dart", line 307, in _startIsolate.<fn>
  File "isolate_patch.dart", line 174, in _RawReceivePortImpl._handleMessage
```

I am tracking this problem, I think it happens only on android device, later this week I home I will have more data on it.

**Comment by vinicius-animo** [comment]
@bejavu, it looks like this happens because you're trying to access the plugin in an `Isolate`.
If this is the case, you will need to register the segment plugin channel to access it.

[Here's a stakoverflow post for a problem that looks similar](https://stackoverflow.com/questions/57466952/unable-to-understand-flutter-dart-plugin-isolate-workaround-for-window-sendpla).

**Comment by bejavu** [comment]
@vinicius-animo 
We use Isolate for just one thread, it should not be a problem, we are not encountered it with any other plugin...
Are you sure this is the issue?

**Comment by vinicius-animo** [comment]
@bejavu, there's an update (still being tested, but apparently working fine) that addresses this issue at [this repo](https://github.com/animo-wellness/flutter-segment).
Can you test from this repo source and report if it fixes your issue? I'll soon create the PR (after some more internal tests).

After we migrated to Flutter 1.12+ we started getting those messages and decided to implement the [new Android plugins APIs](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration).

**Comment by bejavu** [comment]
> @bejavu, there's an update (still being tested, but apparently working fine) that addresses this issue at [this repo](https://github.com/animo-wellness/flutter-segment).
> Can you test from this repo source and report if it fixes your issue? I'll soon create the PR (after some more internal tests).
> 
> After we migrated to Flutter 1.12+ we started getting those messages and decided to implement the [new Android plugins APIs](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration).

We will today, Thanks!

**Comment by bejavu** [comment]
lets see if this works:

https://github.com/fuseio/fuse-wallet/pull/175/files

Events are firing well, 
waiting to see if I get the error in sentry

**Comment by MaiKaY** [comment]
Hi guys,
we just released version `2.0.0`(https://pub.dev/packages/flutter_segment)

Is this issues solved with `2.0.0`?

**Comment by bejavu** [comment]
No, sorry,
"MissingPluginException(No implementation found for method identify on channel flutter_segment)" 
Error keep on firing to sentry.

**Comment by MaiKaY** [comment]
Hi @bejavu,
sad to hear that.
Could you please share the code how you implemented it?

Thanks.

**Comment by bejavu** [comment]
yes, luckily our code is open source so you can see it here:
https://github.com/fuseio/fuse-wallet

I think that this bug is related to the way we start the app inside a zoned thread:
https://github.com/fuseio/fuse-wallet/blob/master/lib/main.dart#L29

**Comment by MaiKaY** [comment]
Could you try to add `WidgetsFlutterBinding.ensureInitialized();` in the very first line of your `main()`

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  String configFile = String.fromEnvironment('CONFIG_FILE', defaultValue: '.env_prod');
  ...
```

**Comment by bejavu** [comment]
We just did!
now we pray 🙏

**Comment by bejavu** [comment]
sorry to say, the errors still remains

**Comment by vinicius-animo** [comment]
Hi @bejavu. There's a PR to fix that. Can you check?

**Comment by LiorAgnin** [comment]
Hi @vinicius-animo,
We tested the PR, Looks like it has fixed the issue.

**Comment by MaiKaY** [comment]
We just released `2.0.1`.

@vinicius-animo thanks for your contribution.

**Comment by hanspeteroliver** [comment]
Hi, I'm running on 2.0.2 and I get the same expectation too, only on Android though. If I downgrade on 2.0.1 the error still persists. Anyone else encountering this?
