### ISSUE TITLE
Crash on IOS

### ISSUE THREAD

**Issue by victortimsit** [claimsforce-gmbh/flutter-segment#68]
Hi there,

Uppon installing flutter_segment like in the docs

```
// in ios/Podfile

pod 'Analytics', '~> 3.0'
```

and running on an IOS device, it crashes on startup:

```
Error output from Xcode build:
↳
    objc[5255]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x208105160) and
    /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x11684c2b8). One of the two will be used. Which one is
    undefined.
    objc[5255]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x2081051b0) and
    /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x11684c308). One of the two will be used. Which one is
    undefined.
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/victortimsit/Documents/dev/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-7.2.0+1/ios/Classes/GeolocatorPlugin.m:150:11: warning:
    'openURL:' is deprecated: first deprecated in iOS 10.0 [-Wdeprecated-declarations]
              openURL:[NSURL URLWithString:UIApplicationOpenSettingsURLString]];
              ^~~~~~~
              openURL:options:completionHandler:
    In module 'UIKit' imported from /Users/victortimsit/Documents/dev/zigg/ios/Pods/Target Support Files/geolocator/geolocator-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/UIK
    it.framework/Headers/UIApplication.h:123:1: note: 'openURL:' has been explicitly marked deprecated here
    - (BOOL)openURL:(NSURL*)url API_DEPRECATED_WITH_REPLACEMENT("openURL:options:completionHandler:", ios(2.0, 10.0))
    NS_EXTENSION_UNAVAILABLE_IOS("");
    ^
    1 warning generated.
    /Users/victortimsit/Documents/dev/flutter/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.0/ios/Classes/Extensions/CLPlacemarkExtensions.m:23:73:
    warning: 'kABPersonAddressStreetKey' is deprecated: first deprecated in iOS 9.0 - use CNPostalAddress.street [-Wdeprecated-declarations]
                street = [[self addressDictionary] objectForKey:(NSString *)kABPersonAddressStreetKey];
                                                                            ^
    In module 'AddressBook' imported from
    /Users/victortimsit/Documents/dev/flutter/.pub-cache/hosted/pub.dartlang.org/geocoding-2.0.0/ios/Classes/Extensions/CLPlacemarkExtensions.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/Add
    ressBook.framework/Headers/ABPerson.h:113:29: note: 'kABPersonAddressStreetKey' has been explicitly marked deprecated here
    AB_EXTERN const CFStringRef kABPersonAddressStreetKey AB_DEPRECATED("use CNPostalAddress.street");
                                ^
    1 warning generated.
    /Users/victortimsit/Documents/dev/zigg/ios/Pods/Reachability/Reachability.m:465:63: warning: cast to smaller integer type 'unsigned int' from
    'Reachability *' [-Wpointer-to-int-cast]
                                 NSStringFromClass([self class]), (unsigned int) self, [self currentReachabilityFlags]];
                                                                  ^~~~~~~~~~~~~~~~~~~
    1 warning generated.
    /Users/victortimsit/Documents/dev/zigg/ios/Pods/Reachability/Reachability.m:465:63: warning: cast to smaller integer type 'unsigned int' from
    'Reachability *' [-Wpointer-to-int-cast]
                                 NSStringFromClass([self class]), (unsigned int) self, [self currentReachabilityFlags]];
                                                                  ^~~~~~~~~~~~~~~~~~~
    1 warning generated.
    2 warnings generated.
    1 warning generated.
    2 warnings generated.
    /Users/victortimsit/Documents/dev/zigg/ios/Pods/AppAuth/Source/AppAuth/iOS/OIDExternalUserAgentIOS.m:168:58: warning: 'openURL:' is deprecated:
    first deprecated in iOS 10.0 [-Wdeprecated-declarations]
        openedUserAgent = [[UIApplication sharedApplication] openURL:requestURL];
                                                             ^~~~~~~
                                                             openURL:options:completionHandler:
    In module 'UIKit' imported from /Users/victortimsit/Documents/dev/zigg/ios/Pods/Target Support Files/AppAuth/AppAuth-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/UIK
    it.framework/Headers/UIApplication.h:123:1: note: 'openURL:' has been explicitly marked deprecated here
    - (BOOL)openURL:(NSURL*)url API_DEPRECATED_WITH_REPLACEMENT("openURL:options:completionHandler:", ios(2.0, 10.0))
    NS_EXTENSION_UNAVAILABLE_IOS("");
    ^
    1 warning generated.
    /Users/victortimsit/Documents/dev/zigg/ios/Pods/AppAuth/Source/AppAuth/iOS/OIDExternalUserAgentIOSCustomBrowser.m:148:42: warning: 'openURL:' is
    deprecated: first deprecated in iOS 10.0 [-Wdeprecated-declarations]
          [[UIApplication sharedApplication] openURL:_appStoreURL];
                                             ^~~~~~~
                                             openURL:options:completionHandler:
    In module 'UIKit' imported from /Users/victortimsit/Documents/dev/zigg/ios/Pods/Target Support Files/AppAuth/AppAuth-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/UIK
    it.framework/Headers/UIApplication.h:123:1: note: 'openURL:' has been explicitly marked deprecated here
    - (BOOL)openURL:(NSURL*)url API_DEPRECATED_WITH_REPLACEMENT("openURL:options:completionHandler:", ios(2.0, 10.0))
    NS_EXTENSION_UNAVAILABLE_IOS("");
    ^
    /Users/victortimsit/Documents/dev/zigg/ios/Pods/AppAuth/Source/AppAuth/iOS/OIDExternalUserAgentIOSCustomBrowser.m:156:61: warning: 'openURL:' is
    deprecated: first deprecated in iOS 10.0 [-Wdeprecated-declarations]
      BOOL openedInBrowser = [[UIApplication sharedApplication] openURL:requestURL];
                                                                ^~~~~~~
                                                                openURL:options:completionHandler:
    In module 'UIKit' imported from /Users/victortimsit/Documents/dev/zigg/ios/Pods/Target Support Files/AppAuth/AppAuth-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk/System/Library/Frameworks/UIK
    it.framework/Headers/UIApplication.h:123:1: note: 'openURL:' has been explicitly marked deprecated here
    - (BOOL)openURL:(NSURL*)url API_DEPRECATED_WITH_REPLACEMENT("openURL:options:completionHandler:", ios(2.0, 10.0))
    NS_EXTENSION_UNAVAILABLE_IOS("");
    ^
    2 warnings generated.
    1 warning generated.
    /Users/victortimsit/Documents/dev/zigg/ios/Pods/Analytics/Analytics/Vendor/SEGReachability.m:495:89: warning: cast to smaller integer type
    'unsigned int' from 'SEGReachability *' [-Wpointer-to-int-cast]
                                                           NSStringFromClass([self class]), (unsigned int)self];
                                                                                            ^~~~~~~~~~~~~~~~~~
    1 warning generated.
    /Users/victortimsit/Documents/dev/zigg/ios/Pods/Analytics/Analytics/Vendor/SEGReachability.m:495:89: warning: cast to smaller integer type
    'unsigned int' from 'SEGReachability *' [-Wpointer-to-int-cast]
                                                           NSStringFromClass([self class]), (unsigned int)self];
                                                                                            ^~~~~~~~~~~~~~~~~~
    1 warning generated.
    Command CompileSwift failed with a nonzero exit code
    While building module 'Segment_Amplitude' imported from
    /Users/victortimsit/Documents/dev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_segment-3.1.2/ios/Classes/FlutterSegmentPlugin.m:5:
    In file included from <module-includes>:1:
    In file included from /Users/victortimsit/Documents/dev/zigg/ios/Pods/Target Support Files/Segment-Amplitude/Segment-Amplitude-umbrella.h:13:
    /Users/victortimsit/Documents/dev/zigg/ios/Pods/Segment-Amplitude/Pod/Classes/SEGAmplitudeIntegration.h:2:9: error: include of non-modular header
    inside framework module 'Segment_Amplitude.SEGAmplitudeIntegration':
    '/Users/victortimsit/Documents/dev/zigg/ios/Pods/Headers/Public/Analytics/SEGIntegration.h' [-Werror,-Wnon-modular-include-in-framework-module]
    #import <Analytics/SEGIntegration.h>
            ^
    While building module 'Segment_Amplitude' imported from
    /Users/victortimsit/Documents/dev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_segment-3.1.2/ios/Classes/FlutterSegmentPlugin.m:5:
    In file included from <module-includes>:1:
    In file included from /Users/victortimsit/Documents/dev/zigg/ios/Pods/Target Support Files/Segment-Amplitude/Segment-Amplitude-umbrella.h:14:
    /Users/victortimsit/Documents/dev/zigg/ios/Pods/Segment-Amplitude/Pod/Classes/SEGAmplitudeIntegrationFactory.h:2:9: error: include of non-modular
    header inside framework module 'Segment_Amplitude.SEGAmplitudeIntegrationFactory':
    '/Users/victortimsit/Documents/dev/zigg/ios/Pods/Headers/Public/Analytics/SEGIntegrationFactory.h'
    [-Werror,-Wnon-modular-include-in-framework-module]
    #import <Analytics/SEGIntegrationFactory.h>
            ^
    2 errors generated.
    /Users/victortimsit/Documents/dev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_segment-3.1.2/ios/Classes/FlutterSegmentPlugin.m:5:9: fatal
    error: could not build module 'Segment_Amplitude'
    #import <Segment_Amplitude/SEGAmplitudeIntegrationFactory.h>
     ~~~~~~~^
    3 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

```

I tried the following:

`flutter clean`
`cd ios/ && pod install && pod repo update`

What am I missing here ?

Cheers!

**Comment by theochampion** [comment]
Same problem here on mac M1!

**Comment by MaiKaY** [comment]
Hi @victortimsit,
we just released a new version `3.1.3`. Could you please try and confirm that the issue is solved after upgrading to version `3.1.3`?

**Comment by saharvx9** [comment]
still not working on m1
i get this error when i am doing pod install:

```
[!] CocoaPods could not find compatible versions for pod "flutter_segment":
  In Podfile:
    flutter_segment (from `.symlinks/plugins/flutter_segment/ios`)

Specs satisfying the `flutter_segment (from `.symlinks/plugins/flutter_segment/ios`)` dependency were found, but they required a higher minimum deployment target.
```
